# Generated by Django 4.1.2 on 2022-10-25 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_released', models.DateField(default=datetime.datetime.today)),
                ('likes', models.CharField(max_length=1000)),
                ('music_id', models.CharField(max_length=100)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Musicapp.artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4000)),
                ('song_title', models.CharField(max_length=100)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Musicapp.song')),
            ],
        ),
    ]
