# Generated by Django 4.1.2 on 2022-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0003_alter_song_date_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='music_id',
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
