# Generated by Django 4.1.2 on 2022-10-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0004_remove_song_music_id_alter_song_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='Artiste',
        ),
    ]
