# Generated by Django 4.1.2 on 2022-10-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Musicapp', '0006_alter_lyric_song_alter_song_artiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='id',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(),
        ),
    ]
